<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>อายุนะจ้ะ</description>
   <name>auto_age</name>
   <tag></tag>
   <elementGuidId>a2a0f5ff-1b29-4de0-a268-11018d34d8c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;age&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
