<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>ใส่วันเกิดนะจ้ะ</description>
   <name>birthday_in</name>
   <tag></tag>
   <elementGuidId>767db68d-daf1-4bfe-b587-55712b40f13e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/section/div/div/div/div/form/div[4]/div[2]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
